---
- name: Create GOGS deployment configuration
  template:
    src: gogs-mysql-template.yml
    dest: /tmp/gogs-mysql-template.yml
    force: yes

- name: Execute GOGS deployment configuration
  shell: oc create -f /tmp/gogs-mysql-template.yml

- name: Remove GOGS deployment configuration
  file:
    path: /tmp/gogs-mysql-template.yml
    state: absent